In [2]:
import numpy as np

## Using zeros methods

`zeros`

In [2]:
x = np.zeros(shape=(2,4))

print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
x= np.ones(shape=(2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## Using Fill methods

`fill`

In [4]:
y = np.full(shape=(2,3), fill_value=10.5)

print(y)

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]]


## Two major methods used in numpy for generating number sequences are,

- `arange` : Numbers created based on step value.

Syntax -  **numpy.arange([start, ]stop, [step, ]dtype=None)**



- `linspace` : Numbers created based on size value.

Syntax - **numpy.linspace(start, stop, #num inbetween, endpoint=True, retstep=False, dtype=None)**

In [5]:
x = np.arange(3, 15, 2.5) # 2.5 is step

print(x)

[ 3.   5.5  8.  10.5 13. ]


In [6]:
y = np.linspace(3, 15, 5) # 5 is size of array 'y'

print(y)

[ 3.  6.  9. 12. 15.]


In [3]:
print(np.repeat(3, 4))

[3 3 3 3]


In [4]:
x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [5]:
x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))

[ 2.  7. 12. 17.]


In [6]:
x = np.arange(30).reshape(5,6)
print(x.argmax(axis=1))

[5 5 5 5 5]


In [7]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 
               3]])
print(x + y)

[[-5  1]
 [-1  5]]


## Random Numbers Generator
- `random` module of numpy is used to generate various random sequences.
    1. `rand`
    2. `randint`

In [7]:
np.random.seed(100) # setting seed

x = np.random.rand(2) # 2 random numbers between 0 and 1

print(x)

[0.54340494 0.27836939]


In [8]:
np.random.rand(3, 2)  # shape of (3,2)

array([[0.42451759, 0.84477613],
       [0.00471886, 0.12156912],
       [0.67074908, 0.82585276]])

In [9]:
np.random.seed(100) # setting seed

y = np.random.randint(10, 50, 3) # 3 random integers between 10 and 50

print(y)


[18 34 13]


## Simulating Normal Distribution
- `randn` is used to simulate standard normal distribution.

In [10]:
np.random.seed(100)

x = np.random.randn(3) # Standard normal distribution

print(x)


[-1.74976547  0.3426804   1.1530358 ]


In [11]:
np.random.seed(100)

x = 10 + 2.5*np.random.randn(3) # normal distribution with mean 10 and sd 2.5

print(x)


[ 5.62558632 10.85670101 12.88258951]


## Simulating Binomial Distribution
- `binomial` - takes two arguments

In [12]:
n, p = 10, .5  # number of trials, probability of each trial
s = np.random.binomial(n, p, 100)
# result of flipping a coin 10 times, tested 1000 times.

In [13]:
s

array([1, 3, 6, 6, 3, 5, 7, 4, 4, 3, 4, 8, 6, 4, 6, 4, 5, 7, 6, 4, 4, 4,
       1, 4, 6, 2, 5, 5, 3, 5, 2, 7, 8, 3, 7, 5, 6, 6, 5, 2, 4, 5, 6, 4,
       4, 7, 8, 7, 4, 5, 4, 4, 4, 4, 2, 5, 4, 5, 6, 3, 7, 8, 5, 5, 4, 4,
       4, 4, 4, 8, 8, 5, 6, 4, 3, 5, 5, 3, 5, 9, 5, 4, 6, 6, 4, 6, 5, 4,
       3, 4, 5, 6, 4, 6, 4, 6, 6, 6, 5, 4])

In [14]:
m = np.random.binomial(n,p, (5,5))

In [15]:
m

array([[6, 7, 6, 8, 8],
       [3, 2, 3, 7, 8],
       [4, 4, 5, 4, 5],
       [6, 5, 6, 5, 1],
       [5, 5, 5, 4, 5]])

In [16]:
print(np.linspace(1, 10, 5))
print(np.arange(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [17]:
z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


## Define a ndarray x2, whose shape is (3, 2, 2) and contains all 1's.

In [18]:
x2 = np.ones(shape=(3,2,2))
x2

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## Define a ndarray x3, whose shape is (4,4) and contains 1's on diagonal and 0's elsewhere.

In [19]:
x3 = np.eye(4,4)

In [20]:
x3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Define a random 3-D array x4 of shape (3, 4, 2) and of numbers between 0 and 1.


In [21]:
x4 = np.random.rand(3,4,2)
x4

array([[[0.44517663, 0.09043279],
        [0.27356292, 0.9434771 ],
        [0.02654464, 0.03999869],
        [0.28314036, 0.58234417]],

       [[0.9908928 , 0.99264224],
        [0.99311737, 0.11004833],
        [0.66448145, 0.52398683],
        [0.17314991, 0.94296024]],

       [[0.24186009, 0.99893227],
        [0.58269382, 0.183279  ],
        [0.38684542, 0.18967353],
        [0.41077067, 0.59468007]]])

## Simulate a random normal distribution of 20 elements, whose mean is 5 and standard deviation 2.5 . Capture the result in x5.


In [22]:
x5 = 5 + 2.5*np.random.randn(20)
x5

array([ 4.36890991,  4.72401332,  9.56000283,  6.77597696,  0.63328898,
       -0.03928376,  2.90659303,  2.37361249,  3.39183268,  3.74450153,
       -2.50202892,  5.71669712,  6.24701896,  3.49084728,  8.27235271,
        8.18977359,  1.78501731,  3.43560892,  5.85427698,  4.67306745])

## Define a ndarray x6, having first 20 even numbers.


In [23]:
x6 = np.arange(2,41,2)
x6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

## Define a ndarray x7, having equally spaced 30 numbers between 10 and 20.

In [24]:
x7 = np.linspace(10,20,30)
x7

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

## You can reshape an array like below

In [25]:
y = x7.reshape(5,6)
print(y, end='\n\n')


[[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793]
 [12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345]
 [14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897]
 [16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448]
 [18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]]



In [26]:
z = x7.reshape(2,3,5)
print(z, '\n\n')


[[[10.         10.34482759 10.68965517 11.03448276 11.37931034]
  [11.72413793 12.06896552 12.4137931  12.75862069 13.10344828]
  [13.44827586 13.79310345 14.13793103 14.48275862 14.82758621]]

 [[15.17241379 15.51724138 15.86206897 16.20689655 16.55172414]
  [16.89655172 17.24137931 17.5862069  17.93103448 18.27586207]
  [18.62068966 18.96551724 19.31034483 19.65517241 20.        ]]] 




## Stacking arrays vertically
Two or more arrays can be joined vertically using the generic `vstack` method.

In [27]:
x = np.array([[-1, 1], [-3, 3]])

y = np.array([[-2, 2], [-4, 4]])


np.vstack((x,y))


array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

## Stacking arrays horizontally
Two or more arrays can be joined horizontally using the generic `hstack` method.

In [28]:
x = np.array([[-1, 1], [-3, 3]])

y = np.array([[-2, 2], [-4, 4]])

z = np.array([[-5, 5], [-6, 6]])



np.hstack((x,y,z))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

## Splitting arrays Vertically
Arrays can be split vertically using the generic `vsplit` method.

In [29]:
x = np.arange(30).reshape(6, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [30]:
res = np.vsplit(x, 2)
res

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [31]:
print(res[0], end='\n\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]



In [32]:
print(res[1])

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


## It is also possible to split at specific row numbers using vsplit.

In [33]:
x = np.arange(30).reshape(6, 5)



res = np.vsplit(x, (2, 5))

print(res[0], end='\n\n')

print(res[1], end='\n\n')

print(res[2])


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[25 26 27 28 29]]


In [34]:

x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]


In [37]:
x = np.arange(6).reshape(2,3)
print(x)
y = np.hsplit(x,(2,))
print(y[0])

[[0 1 2]
 [3 4 5]]
[[0 1]
 [3 4]]


## Create a 2-D array p, of shape (2, 2) with elements 3, 6, 9, 12.

## Create a 2-D array q, of shape (2, 3) with elements 15, 18, 21, 24, 27, 30.

## Join the two arrays p and q horizontally.

In [40]:
p = np.array([3,6,9,12]).reshape(2,2)
q = np.array([15,18,21,24,27,30]).reshape(2,3)
r = np.hstack((p,q))
r

array([[ 3,  6, 15, 18, 21],
       [ 9, 12, 24, 27, 30]])