## Indexing, Slicing a 1-D ndarray

Slicing refers to extracting a portion of existing array.

This can be achieved with a slice object.

A slice object is of the form `start:end:step`. All three are optional.

Having only a single number inside square brackets refer to start index.


In [1]:
import numpy as np

In [2]:
x = np.array([5, 10, 15, 20, 25, 30, 35])

print(x[1])  # Indexing

print(x[1:6]) # Slicing

print(x[1:6:3]) # Slicing


10
[10 15 20 25 30]
[10 25]


## Indexing, Slicing a 2-D ndarray

Two slice objects, one for each dimension, are required to slice a 2-D array.

They are separated by a `comma (,)` and having only a single slice object inside square brackets refers to first dimension.

All elements of a single dimension can be referred with a `colon (:)`.

In [9]:
y = np.array([[0, 1, 2],

              [3, 4, 5]])

print(y[1:2, 1:3]) 

print(y[1])   

print(y[:, 1]) 

[[4 5]]
[3 4 5]
[1 4]


In the below 3d Array example, it has 3 arrays, each array with 2,2 array.

In [21]:
z = np.array([[[-1, 1], 
               [-2, 2]],

              [[-4, 4], 
               [-5, 5]],

              [[-7, 7], 
               [-9, 9]]])

print(z[1,:,1], end='\n\n')

print(z[1:,1,:], end='\n\n')

print(z[2], end='\n\n')


[4 5]

[[-5  5]
 [-9  9]]

[[-7  7]
 [-9  9]]



## Iterating using 'for'

`for` loop can be used to iterate over every dimensional element.

In [22]:
x = np.array([[-1, 1], 
              [-2, 2]])


for row in x:
    print('Row :',row)

Row : [-1  1]
Row : [-2  2]


## Iterating using 'np.nditer()'
`nditer` method of numpy creates an iterator, which enable accessing each element one after the other.

In [23]:
x = np.array([[0,1], 
              [2, 3]])

for a in np.nditer(x):
    print(a)

0
1
2
3


## Boolean Indexing

Checking if every element of an array satisfies a condition, results in a Boolean array.

This Boolean array can be used as index to `filter elements` that satisfy the condition.

In [26]:
x = np.arange(10).reshape(2,5)

condition = x % 2 == 0

x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
print(condition)

[[ True False  True False  True]
 [False  True False  True False]]


In [28]:
print(x[condition])

[0 2 4 6 8]


In [29]:
x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [31]:
x = np.arange(12).reshape(3,4)
print(x[-1:,])

[[ 8  9 10 11]]


In [32]:
x = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])
print(x[[0, 1, 2], 
        [0, 1, 1]])

[1 4 6]


In [33]:
x = np.arange(12).reshape(3,4)
print(x[-2])

[4 5 6 7]


In [35]:
x = np.array([[0, 1], 
              [1, 1], 
              [2, 2]])
y = x.sum(-1)
print(x[y < 2, :])

[[0 1]]


In [36]:
x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]


In [37]:
print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [38]:
print(np.linspace(1, 10, 5))
print(np.arange(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [39]:
x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
print(y)

[[0 0 0]
 [0 0 0]]


In [40]:
x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]


In [41]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]
