In [1]:
import numpy as np

In [2]:
x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [3]:
print(np.linspace(1, 10, 5))
print(np.arange(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [4]:
x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]


In [5]:
x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]


In [6]:
x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]


In [7]:
x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))

[ 2.  7. 12. 17.]


In [8]:
x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [9]:
x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [10]:

x = np.arange(30).reshape(3,5,2)
print(x[1][::2][1])

[14 15]


In [11]:
x = np.arange(12).reshape(3,4)
print(x[-2])

[4 5 6 7]


In [12]:
x = np.arange(30).reshape(3,5,2)
print(x[1,::2,1])

[11 15 19]
